version: '3.8'

services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./my-postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
